### ISSUE TITLE
Random short(96 bit) nonce values for AES-GCM are ill advised

### ISSUE THREAD

**Issue by zmanian** [palantir/serde-encrypted-value#1]
When using random nonces with an AEAD, it is generally recommended to use a construction with a longer nonce. libsodium has xchacha20-poly1035 with 192 bit nonces for this purpose. Using 96 bit nonces, there is a 0.1 % chance of a nonce collision that would leak the key to an attacker with access to both cypher texts after generating 13 trillion cypher texts.

Maybe consider switching to either a counter based on nonce or using xchacha if you need random nonces.

**Comment by sfackler** [comment]
This mirrors the implementation of https://github.com/palantir/encrypted-config-value - you may want to file there.

I'm not familiar with a use case of these libraries where a single key is used to generate more than 10 encrypted values, not to mention 13 trillion.

**Comment by zmanian** [comment]
It's fine if the number of generated values under a key is small like config values. Then you start encrypting session cookies in a distributed infrastructure and there is much sadness

**Comment by sfackler** [comment]
Fortunately this crate and the associated Java libraries only encrypt config values.
