### ISSUE TITLE
iv counter makes library unusable

### ISSUE THREAD

**Issue by Grannath** [palantir/serde-encrypted-value#5]
While I appreciate the security effort from #1 , now it is impossible to use an existing key for encryption. This is a serious incompatibility with previous versions.

This means the library is unusable for me to store config values. Now, every time I need to add or change a value, I have to rotate the encryption key and reencrypt everything. That is very tedious, and completely unnecessary.

I am no security expert. But knowing it's a counter, I can always tell that encrypted values have an iv value of 0, 1, 2, at most 10. That sounds hardly secure.

Also, you could have used something like a timestamp, maybe hashed. It is also effectively a counter, but one that does not reset for every round of encryption. This would also again enable use of keys read from a file.

Unfortunately, I cannot work around this. The fields are all private, so I cannot hack together a key with ReadWrite mode. Please fix this.

**Comment by sfackler** [comment]
> While I appreciate the security effort from #1 , now it is impossible to use an existing key for encryption. 

That was the intention.

> This is a serious incompatibility with previous versions.

That's why it was made in a major version bump.

> This means the library is unusable for me to store config values. Now, every time I need to add or change a value, I have to rotate the encryption key and reencrypt everything. That is very tedious, and completely unnecessary.

Is it unusable, or usable but tedious?

> I am no security expert. But knowing it's a counter, I can always tell that encrypted values have an iv value of 0, 1, 2, at most 10. That sounds hardly secure.

IVs are not secret values. The only requirement is that the same IV is never used to encrypt 2 messages with the same key. They are directly encoded in the serialized blob along side the encrypted data! There are some attacks that can be made more difficult with unpredictable nonces, so we should probably use the same approach as TLS 1.3 and XOR the counter with a random value generated along with the key.

> Also, you could have used something like a timestamp, maybe hashed. It is also effectively a counter, but one that does not reset for every round of encryption. This would also again enable use of keys read from a file.

Nothing would prevent the same key from being used to encrypt two values at the same timestamp, resulting in a reused IV.

You're welcome to continue using the old release, but be aware of the dangers of encrypting an unboundedly large number of values with the same key and random nonces.

**Comment by Grannath** [comment]
So, just for clarification:

My normal workflow, without this library or something else, to change or add a secret, is as follows.
1. Put the new secret value into 1password or some other secure store.
2. Put the new secret into the CI in some manner, or directly into the environment, so it is available to the application.
3. Potentially release the app.
4. Hope I do not have to roll back.

With your library, I can simplify it:
1. Put the new secret into the config file in encrypted form.
2. Release it.

With the new update, this becomes:
1. Generate a new encryption key and reencrypt all existing values.
2. Put the new value into the config file as well, using the new key.
3. Put the new key into 1password, or some other secure location.
4. Make the new key available in the CI.
5. Release the app.
6. Hope I do not have to roll back.

Thinking about it, that is not quite true. Steps 1 and 2 need to be done at the same time, because as soon as my util exits, the key is lost for encryption and I have to start over. So, please again explain to me what the use case for this library is. I just don't see it.

And all this to protect from an attack that is possible on every scenario that has keys stored in a file. Every certificate, every private SSH key, has the exact same issue. But you don't prevent people from saving them. Imagine SSH keys had a counter, and you would generate a new one every time you restart the SSH agent. It would become completely unusable. You rotate server certificates, for example, to protect against attacks. But just imagine you would need a new certificate every time a server restarts. And it gets even worse in a distributed system.

People need to rotate their keys. But how often to do this depends entirely on how they are used. A library cannot reasonably enforce this.

**Comment by sfackler** [comment]
> Every certificate, every private SSH key, has the exact same issue.

No, they don't. SSH keys are asymmetric keys (e.g. RSA or ECDSA) which are used during the SSH handshake to negotiate an ephemeral key for the symmetric cipher used to encrypt the data transferred over the connection.

This is a very specific issue that affects CTR-based block cipher modes like GCM. It is not "people should sometimes rotate keys".
